module.exports = {

    extends: [
        "eslint:recommended",
        require.resolve('./rules/import'),
        require.resolve('./rules/prettier')
    ],
    plugins: [
        'import',
        'babel',
        'prettier'
    ],
    env: {
        node: true,
        jest: true,
        amd: true,
        es6: true,
    },
    rules: {
            'array-bracket-spacing':[ 1,'never'],
            'array-callback-return': 1,
            'arrow-body-style': 0,
            'arrow-parens': [1, 'always'],

            'block-scoped-var': 1,
            'block-spacing': 1,
            'brace-style': 1,

            camelcase: 0,
            'class-methods-use-this': 0,
            'comma-dangle': 1,
            'comma-spacing': 1,
            'consistent-return': 1,
            curly: 1,

            'default-case': 1,
            'dot-notation': ['warn', { allowPattern: '^[a-z]+(_[a-z]+)+$' }],

            'eol-last': 1,

            'func-call-spacing': 1,
            'func-names': 1,
            'function-paren-newline': 0,

            'global-require': 0,
            'guard-for-in': 1,

            'jsx-quotes': [ 1, 'prefer-double' ],

            'key-spacing': [ 1, { beforeColon: false, afterColon: true } ],

            'keyword-spacing': 1,

            'lines-between-class-members': 1,

            'max-len': 0,
            'max-classes-per-file': 0,

            'new-cap': 1,
            'new-parens': 1,
            'newline-per-chained-call': 0,
            'no-bitwise': 1,
            'no-cond-assign': 1,
            'no-confusing-arrow': 1,
            'no-continue': 1,
            'no-else-return': 1,
            'no-extra-semi': 1,
            'no-lonely-if': 1,
            'no-loop-func': 1,
            'no-mixed-operators': 1,
            'no-mixed-spaces-and-tabs': 1,
            'no-multi-assign': 1,
            'no-multi-spaces': 1,
            'no-multiple-empty-lines': 1,
            'no-nested-ternary': 1,
            'no-param-reassign': 1,
            'no-plusplus': [1, { allowForLoopAfterthoughts: true }],
            'no-prototype-builtins': 1,
            'no-restricted-syntax': 1,
            'no-return-assign': 1,
            'no-sequences': 1,
            'no-shadow': 1,
            'no-spaced-func': 1,
            'no-tabs': 1,
            'no-throw-literal': 1,
            'no-trailing-spaces': 1,
            'no-undef': 2,
            'no-underscore-dangle': 0,
            'no-unneeded-ternary': 1,
            'no-unused-expressions': 0,
            'no-unused-vars': 1,
            'no-use-before-define': 1,
            'no-useless-concat': 1,
            'no-useless-escape': 1,
            'no-useless-rename': 1,
            'no-useless-return': 1,
            'no-var': 1,
            'no-whitespace-before-property': 1,
            'object-curly-newline': 'off',
            'object-curly-spacing': 1,
            'object-property-newline': 1,
            'object-shorthand': 1,
            'one-var': 1,
            'one-var-declaration-per-line': 1,
            'operator-assignment': 1,
            'operator-linebreak': 0,

            'padded-blocks': 1,
            'prefer-arrow-callback': 1,
            'prefer-const': 1,
            'prefer-destructuring': 1,
            'prefer-object-spread': 1,
            'prefer-promise-reject-errors': 1,
            'prefer-rest-params': 1,
            'prefer-spread': 1,
            'prefer-template': 1,

            'quote-props': 1,
            quotes: 1,

            radix: 1,
            semi: 1,
            'semi-spacing': 1,
            'space-before-blocks': 1,
            'space-before-function-paren': 1,
            'space-in-parens': 1,
            'space-infix-ops': 1,
            'space-unary-ops': 1,
            'spaced-comment': 1,
            strict: 1,
            'switch-colon-spacing': 0,
            'vars-on-top': 1,
            'wrap-iife': 0,
            'yoda': 1,
            'arrow-spacing':1,
            'generator-star-spacing':1,
            'no-useless-computed-key':1,
            'no-useless-constructor':1,
            'prefer-numeric-literals':1,
            'rest-spread-spacing':1,
            'symbol-description':1,
            'template-curly-spacing':1,
            'yield-star-spacing':1,
            'no-label-var':1,
            'no-restricted-globals':1,
            'no-undef-init':1,
            'comma-style':1,
            'computed-property-spacing':1,
            'linebreak-style':1,
            'lines-around-directive':1,
            'no-new-object':1,
            'nonblock-statement-body-position':1,
            'semi-style':1,
            'template-tag-spacing':1,
            'unicode-bom':1,
            'no-buffer-constructor':1,
            'no-new-require':2,
            'no-path-concat':2,
            'no-await-in-loop':2,
            'no-console':1,
            'no-template-curly-in-string':1,
            'dot-location':1,
            'eqeqeq':1,
            'no-alert':1,
            'no-caller':1,
            'no-eval':1,
            'no-extend-native':1,
            'no-extra-bind':1,
            'no-extra-label':1,
            'no-floating-decimal':1,
            'no-implied-eval':2,
            'no-iterator':2,
            'no-labels':2,
            'no-lone-blocks':2,
            'no-multi-str':2,
            'no-new':2,
            'no-new-func':2,
            'no-new-wrappers':2,
            'no-octal-escape':2,
            'no-proto':2,
            'no-restricted-properties':2,
            'no-return-await':2,
            'no-script-url':2,
            'no-self-compare':2,
            'no-void':2

        }
}
