module.exports = {
    "extends": ["../typeScript/index.js",
        require.resolve('./rules/jsx-a11y'),
        require.resolve('./rules/jsx'),
        require.resolve('./rules/hooks')
    ],
    env: {
        browser: true,
        commonjs: true
    },
    settings:{react: { version: 'detect', pragma: 'React' }},
    plugins: ['react',  'react-hooks', 'jsx-a11y'],
    rules: {
        'react/button-has-type': [1,{ button: true, submit: true, reset: false }],
        'react/default-props-match-prop-types': 1,
        'react/destructuring-assignment': 0,
        'react/forbid-prop-types': 1,
        'react/no-access-state-in-setstate': 1,
        'react/no-array-index-key': 1,
        'react/no-did-mount-set-state': 1,
        'react/no-find-dom-node': 1,
        'react/no-is-mounted': 1,
        'react/no-multi-comp': 0,
        'react/no-redundant-should-component-update': 1,
        'react/no-string-refs': 1,
        'react/no-this-in-sfc': 1,
        'react/no-unescaped-entities': 1,
        'react/no-unused-prop-types': 1,
        'react/no-unused-state': 1,
        'react/prefer-es6-class': 1,
        'react/prefer-stateless-function': 1,
        'react/prop-types': 0,
        'react/require-default-props': 0,
        'react/self-closing-comp': 1,
        'react/sort-comp': 1,
        'react/state-in-constructor': 0,
        'react/static-property-placement': 1,
        'react/style-prop-object': 1,
        'react/no-danger':2,
        'react/no-deprecated':2,
        'react/no-did-update-set-state':2,
        'react/no-will-update-set-state':2,
        'react/no-unknown-property':2,
        'react/react-in-jsx-scope':2,
        'react/require-render-return':2,
        'react/no-render-return-value':2,
        'react/no-danger-with-children':2,
        'react/no-children-prop':2,
        'react/forbid-foreign-prop-types':2,
        'react/void-dom-elements-no-children':2,
        'react/no-typos':2,

    }
}
